#!/bin/bash
# Fixed build prosess for mac os (tested on sdk 10.12)
# Created by p0zzy (aka p0Zitive)

export CXXFLAGS="-std=c++14 -stdlib=libc++"
export LDFLAGS="-stdlib=libc++"

export CC="clang"
export CXX="clang++"
export LD="clang++"

./configure $1 $2 $3 $4 $5 $6 $7 $8 $9

